import { Job } from "@/types/job";

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Pastor",
    description: "We are seeking a passionate and experienced Senior Pastor to lead our growing congregation of 500+ members. The ideal candidate will have a heart for discipleship, a vision for community outreach, and strong preaching abilities. You will oversee all ministry areas and work closely with our elder board to shepherd the church.",
    category: "Pastoral",
    employmentType: "Full-time",
    workArrangement: "On-site",
    location: "Austin, TX",
    church: {
      id: "c1",
      name: "Grace Community Church",
    },
    salary: {
      min: 85000,
      max: 110000,
      type: "annual",
    },
    postedAt: "2026-02-20",
    qualifications: "Master of Divinity or equivalent seminary degree required. Minimum 10 years pastoral experience. Strong leadership and communication skills.",
    responsibilities: "Lead Sunday worship services. Provide pastoral care and counseling. Oversee staff and volunteer teams. Develop and cast vision for church growth.",
  },
  {
    id: "2",
    title: "Worship Leader",
    description: "Join our dynamic worship team as the primary Worship Leader. You will lead our congregation in Spirit-filled worship, develop and mentor volunteer musicians, and collaborate with pastoral staff to create meaningful worship experiences.",
    category: "Worship & Music",
    employmentType: "Full-time",
    workArrangement: "On-site",
    location: "Nashville, TN",
    church: {
      id: "c2",
      name: "Hillside Baptist Church",
    },
    salary: {
      min: 55000,
      max: 70000,
      type: "annual",
    },
    postedAt: "2026-02-22",
    qualifications: "Proficiency in guitar and/or piano required. Experience leading contemporary worship. Heart for developing worship teams.",
    responsibilities: "Lead 2-3 worship services weekly. Recruit and train volunteer musicians. Plan and coordinate special worship events.",
  },
  {
    id: "3",
    title: "Youth Pastor",
    description: "We're looking for an energetic Youth Pastor to build and lead our student ministry program for grades 6-12. Create engaging programs, mentor young leaders, and partner with parents to disciple the next generation.",
    category: "Youth & Children",
    employmentType: "Full-time",
    workArrangement: "On-site",
    location: "Dallas, TX",
    church: {
      id: "c3",
      name: "First Presbyterian Church",
    },
    salary: {
      min: 48000,
      max: 62000,
      type: "annual",
    },
    postedAt: "2026-02-18",
    qualifications: "Bachelor's degree in ministry or related field. 3+ years youth ministry experience. Background check required.",
    responsibilities: "Plan and lead weekly youth programs. Organize summer camps and retreats. Mentor student leaders. Coordinate with volunteers.",
  },
  {
    id: "4",
    title: "Church Administrator",
    description: "Seeking an organized and detail-oriented Church Administrator to manage daily operations, coordinate staff schedules, oversee facilities, and handle church finances. This role is essential to keeping our ministry running smoothly.",
    category: "Administrative",
    employmentType: "Full-time",
    workArrangement: "Hybrid",
    location: "Phoenix, AZ",
    church: {
      id: "c4",
      name: "Desert Springs Fellowship",
    },
    salary: {
      min: 45000,
      max: 58000,
      type: "annual",
    },
    postedAt: "2026-02-24",
    qualifications: "Bachelor's degree preferred. Experience with church management software. Strong organizational and communication skills.",
    responsibilities: "Manage church calendar and facilities. Process payroll and accounts payable. Coordinate with ministry leaders. Supervise office staff.",
  },
  {
    id: "5",
    title: "Media & Production Director",
    description: "Lead our technical team in creating excellent media experiences for Sunday services, online streaming, and social media content. Oversee all audio, video, lighting, and digital communication.",
    category: "Technical & Media",
    employmentType: "Full-time",
    workArrangement: "On-site",
    location: "Atlanta, GA",
    church: {
      id: "c5",
      name: "Crossroads Church",
    },
    salary: {
      min: 52000,
      max: 68000,
      type: "annual",
    },
    postedAt: "2026-02-21",
    qualifications: "Experience with ProPresenter, live streaming, and audio mixing. Video editing skills. Leadership experience preferred.",
    responsibilities: "Lead Sunday production team. Manage live stream and recording. Create social media content. Maintain technical equipment.",
  },
  {
    id: "6",
    title: "Children's Ministry Coordinator",
    description: "Part-time opportunity to coordinate our children's ministry program for ages birth through 5th grade. Recruit volunteers, plan curriculum, and ensure a safe and fun environment for kids to learn about Jesus.",
    category: "Youth & Children",
    employmentType: "Part-time",
    workArrangement: "On-site",
    location: "Denver, CO",
    church: {
      id: "c6",
      name: "Mountain View Community Church",
    },
    salary: {
      min: 22,
      max: 28,
      type: "hourly",
    },
    postedAt: "2026-02-19",
    qualifications: "Experience working with children. Background check required. First aid/CPR certification preferred.",
    responsibilities: "Coordinate Sunday children's programs. Recruit and train volunteers. Select and implement curriculum. Ensure child safety protocols.",
  },
  {
    id: "7",
    title: "Missions Pastor",
    description: "Lead our global and local missions initiatives. Develop partnerships with missionaries and organizations worldwide. Mobilize our congregation to serve and support missions work.",
    category: "Outreach",
    employmentType: "Full-time",
    workArrangement: "Hybrid",
    location: "Seattle, WA",
    church: {
      id: "c7",
      name: "Evergreen Bible Church",
    },
    salary: {
      min: 58000,
      max: 75000,
      type: "annual",
    },
    postedAt: "2026-02-23",
    qualifications: "Cross-cultural ministry experience. Theological training preferred. Strong relational and organizational skills.",
    responsibilities: "Oversee missions budget and partnerships. Lead short-term mission trips. Develop missions education programs. Support missionary care.",
  },
  {
    id: "8",
    title: "Social Media Manager",
    description: "Remote opportunity to manage our church's social media presence across multiple platforms. Create engaging content, grow our online community, and help extend our ministry reach digitally.",
    category: "Technical & Media",
    employmentType: "Part-time",
    workArrangement: "Remote",
    location: "Remote",
    church: {
      id: "c8",
      name: "New Life Church Online",
    },
    salary: {
      min: 20,
      max: 30,
      type: "hourly",
    },
    postedAt: "2026-02-25",
    qualifications: "Experience with Instagram, Facebook, YouTube, and TikTok. Graphic design skills. Understanding of church culture.",
    responsibilities: "Create and schedule social media content. Engage with online community. Track analytics and growth. Coordinate with ministry teams.",
  },
  {
    id: "9",
    title: "Executive Pastor",
    description: "Serve as the operational leader of our multi-site church. Oversee staff, manage budgets, implement strategic initiatives, and work alongside the Senior Pastor to accomplish our mission.",
    category: "Executive",
    employmentType: "Full-time",
    workArrangement: "On-site",
    location: "Houston, TX",
    church: {
      id: "c9",
      name: "Champions Church",
    },
    salary: {
      min: 95000,
      max: 125000,
      type: "annual",
    },
    postedAt: "2026-02-17",
    qualifications: "MBA or MDiv preferred. 10+ years leadership experience. Multi-site church experience preferred.",
    responsibilities: "Oversee all church operations. Lead and develop staff. Manage church budget. Drive strategic planning.",
  },
  {
    id: "10",
    title: "Facilities Manager",
    description: "Oversee the maintenance and upkeep of our 50,000 sq ft church campus. Manage maintenance staff, coordinate with vendors, and ensure our facilities support excellent ministry.",
    category: "Facilities",
    employmentType: "Full-time",
    workArrangement: "On-site",
    location: "Orlando, FL",
    church: {
      id: "c10",
      name: "Celebration Church",
    },
    salary: {
      min: 48000,
      max: 60000,
      type: "annual",
    },
    postedAt: "2026-02-16",
    qualifications: "Experience in facilities management. HVAC and electrical knowledge preferred. Vendor management experience.",
    responsibilities: "Oversee building maintenance. Manage maintenance team. Coordinate event setups. Handle vendor relationships.",
  },
  {
    id: "11",
    title: "Pastoral Counselor",
    description: "Provide biblical counseling and pastoral care to our congregation. Walk alongside individuals and families through life's challenges with compassion and wisdom rooted in Scripture.",
    category: "Counseling",
    employmentType: "Part-time",
    workArrangement: "Hybrid",
    location: "Chicago, IL",
    church: {
      id: "c11",
      name: "Redeemer Church Chicago",
    },
    salary: {
      min: 30,
      max: 45,
      type: "hourly",
    },
    postedAt: "2026-02-14",
    qualifications: "Licensed counselor or pastoral counseling certification. Biblical counseling training. Experience in church ministry.",
    responsibilities: "Provide individual and couples counseling. Facilitate support groups. Train lay counselors. Coordinate care ministry.",
  },
  {
    id: "12",
    title: "Discipleship Director",
    description: "Lead our discipleship ministry by developing pathways for spiritual growth. Oversee small groups, Bible studies, and mentoring programs that help people grow as followers of Jesus.",
    category: "Education",
    employmentType: "Full-time",
    workArrangement: "On-site",
    location: "San Diego, CA",
    church: {
      id: "c12",
      name: "Anchor Church",
    },
    salary: {
      min: 55000,
      max: 72000,
      type: "annual",
    },
    postedAt: "2026-02-15",
    qualifications: "Theological degree preferred. Small group leadership experience. Curriculum development skills.",
    responsibilities: "Oversee small group ministry. Develop discipleship curriculum. Train group leaders. Create spiritual growth pathways.",
  },
];
